---
refresh_interval: 5 # seconds
max_price: 950 # dollars
urls:
  - https://www.bestbuy.ca/en-ca/product/nvidia-geforce-rtx-3070-8gb-gddr6-video-card-only-at-best-buy/15078017
  - https://www.bestbuy.ca/en-ca/product/msi-nvidia-geforce-rtx-3070-ventus-3x-oc-8gb-gddr6-video-card/15038016
  - https://www.bestbuy.ca/en-ca/product/zotac-nvidia-geforce-rtx-3070-twin-edge-8gb-gddr6x-video-card/15000079
  - https://www.bestbuy.ca/en-ca/product/zotac-nvidia-geforce-rtx-3070-twin-edge-oc-8gb-gddr6x-video-card/15000078
  - https://www.newegg.ca/asus-geforce-rtx-3070-dual-rtx3070-o8g/p/N82E16814126459?Item=N82E16814126459
  - https://www.newegg.ca/asus-geforce-rtx-3070-ko-rtx3070-o8g-gamin/p/N82E16814126466?Description=rtx%203070&cm_re=rtx_3070-_-14-126-466-_-Product
  - https://www.newegg.ca/gigabyte-geforce-rtx-3070-gv-n3070eagle-oc-8gd/p/N82E16814932343?Description=rtx%203070&cm_re=rtx_3070-_-14-932-343-_-Product
  - https://www.newegg.ca/evga-geforce-rtx-3070-08g-p5-3751-kr/p/N82E16814487528?Description=rtx%203070&cm_re=rtx_3070-_-14-487-528-_-Product
  - https://www.newegg.ca/evga-geforce-rtx-3070-08g-p5-3765-kr/p/N82E16814487531?Description=rtx%203070&cm_re=rtx_3070-_-14-487-531-_-Product
  - https://www.newegg.ca/evga-geforce-rtx-3070-08g-p5-3755-kr/p/N82E16814487530?Description=rtx%203070&cm_re=rtx_3070-_-14-487-530-_-Product
  - https://www.newegg.ca/gigabyte-geforce-rtx-3070-gv-n3070gaming-oc-8gd/p/N82E16814932342?Description=rtx%203070&cm_re=rtx_3070-_-14-932-342-_-Product
  - https://www.newegg.ca/evga-geforce-rtx-3070-08g-p5-3767-kr/p/N82E16814487532?Description=rtx%203070&cm_re=rtx_3070-_-14-487-532-_-Product
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=183101
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=183210
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=183099
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=183500
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=183636
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=183208
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=183638
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=183561
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=184167
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=183637
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=183498
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=183209
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=184168
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=183100
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=184743
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=183499
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=183560
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=186197
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=185675
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=186310
  - https://www.canadacomputers.com/product_info.php?cPath=43_557_559&item_id=187683
  - https://www.amazon.ca/MSI-GeForce-256-Bit-Architecture-Graphics/dp/B08KWLMZV4/ref=sr_1_2?dchild=1&keywords=rtx+3070&qid=1612155619&s=electronics&sr=1-2
  - https://www.amazon.ca/MSI-GeForce-Tri-Frozr-Architecture-Graphics/dp/B08KWN2LZG/ref=sr_1_1?dchild=1&keywords=rtx+3070&qid=1612155619&s=electronics&sr=1-1
  - https://www.amazon.ca/MSI-GeForce-RTX-3070-Architecture/dp/B08KWPDXJZ/ref=sr_1_4?dchild=1&keywords=rtx+3070&qid=1612155619&s=electronics&sr=1-4
  - https://www.amazon.ca/Graphics-IceStorm-Advanced-Lighting-ZT-A30700H-10P/dp/B08LF1CWT2/ref=sr_1_3?dchild=1&keywords=rtx+3070&qid=1612155619&s=electronics&sr=1-3
  - https://www.amazon.ca/Graphics-IceStorm-Advanced-Lighting-ZT-A30700E-10P/dp/B08LF32LJ6/ref=sr_1_5?dchild=1&keywords=rtx+3070&qid=1612155619&s=electronics&sr=1-5
  - https://www.amazon.ca/EVGA-08G-P5-3755-KR-GeForce-Cooling-Backplate/dp/B08L8L71SM/ref=sr_1_6?dchild=1&keywords=rtx+3070&qid=1612155619&s=electronics&sr=1-6
  - https://www.amazon.ca/Graphics-DisplayPort-Axial-tech-Protective-Backplate/dp/B08L8LG4M3/ref=sr_1_7?dchild=1&keywords=rtx+3070&qid=1612155619&s=electronics&sr=1-7
  - https://www.amazon.ca/GIGABYTE-Graphics-WINDFORCE-GV-N3070AORUS-M-8GD/dp/B08M14Y3C7/ref=sr_1_8?dchild=1&keywords=rtx+3070&qid=1612155619&s=electronics&sr=1-8
  - https://www.amazon.ca/GIGABYTE-Graphics-WINDFORCE-GV-N3070GAMING-OC-8GD/dp/B08KY266MG/ref=sr_1_9?dchild=1&keywords=rtx+3070&qid=1612155619&s=electronics&sr=1-9
  - https://www.amazon.ca/Graphics-DisplayPort-Bearings-Military-Grade-Certification/dp/B08L8KC1J7/ref=sr_1_15?dchild=1&keywords=rtx+3070&qid=1612155619&s=electronics&sr=1-15
  - https://www.amazon.ca/GeForce-Graphics-DisplayPort-Axial-tech-2-9-Slot/dp/B08L8JNTXQ/ref=sr_1_16?dchild=1&keywords=rtx+3070&qid=1612155619&s=electronics&sr=1-16
...
